---
title: "final project"
author: "Yuanhao Zhu"
date: "4/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##data processing

```{r}
#We use the raw data in sheet 2 for data processing. The transformed data is ill structured. For instance ln1 is 0 and missing values were also assigned value 0. 
library("readxl")
library("dplyr")
rawdata <- read_excel("COVID.xlsx", sheet = "Sheet2",col_names=T,range = cell_cols(1:9))
colnames(rawdata)<-c("CODE","COUNTRY",	"DATE",	"TC",	"TD","STI",	"POP","GDPCAP","HDI")
#a function take natrual log and leave 0 if the cell is 0 and NA if the cell is NA 
avoid_zero_ln<-function(x){
 n=ifelse(x == 0, 0, log(x))
 return(n)
}

data<-rawdata %>% mutate_at(c("TC",	"TD","STI",	"POP","GDPCAP"), avoid_zero_ln)
colnames(data)<-c("CODE","COUNTRY",	"DATE",	"logTC",	"logTD","logSTI",	"logPOP","logGDPCAP","HDI")
#keep both variables in log scale and original ones. 
#The processed data is  called covid. Note that NA values are perserved. 
covid<-cbind(data,rawdata[,c(4:8)])
head(covid)
```

>Data are in both natural log and original scale. 

| Variable Indicator   | Description  | Measurement |
| ------------- |:-------------:| :-----:|
| STI    | Stringency Index | COVID-19 PandemicLockdown |
|  TC    | Total Cases      |  COVID-19 PandemicTotal cases recorded  |
| TD | Total Death     | COVID-19 PandemicDeaths-   |
|  GDPCAP   | GDP Per Capital      |  Economic Growth  |
| HDI | Human Development Index      |  Poverty Alleviation |


```{r}
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("maps")
world_map <- map_data("world")
```



```{r}
world_map <- map_data("world")
deathrate<-c()
for( i in unique(covid$COUNTRY)){
  d<-covid[covid$COUNTRY==i,11]
  p<-covid[covid$COUNTRY==i,13]
  if(all(is.na(p)) |all(is.na(d)) ){rate<-NA}
  else{
  totaldeath<-max(d,na.rm=T)
  population<-max(p,na.rm = T)
  rate<-(totaldeath/population)*100}
  deathrate<-c(deathrate,rate)
}
d_rate<-data.frame(region=unique(covid$COUNTRY), deathrate)
levels(d_rate$region)[levels(d_rate$region)=="United States"] <- "USA"
```

```{r}
comb <- left_join(world_map,d_rate, by = "region")
ggplot(comb, aes(long, lat, group = group))+
  geom_polygon(aes(fill = deathrate ), color = "white")+
  scale_fill_viridis_c(
  alpha = 0.7,
  begin = 0,
  end = 1,
  direction = -1,
  option = "A",
  values = NULL,
  space = "Lab",
  na.value = "grey80",
  guide = "colourbar",
  aesthetics = "fill"
)+labs(title="World Map of Total Death Rate for Each Country",
        x ="Longitude", y = "Latitude7")

```


